DROP TABLE IF EXISTS orderitem CASCADE;
DROP TABLE IF EXISTS suppliermedicine CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS medicine CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;

-- Independent tables
CREATE TABLE client(
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL
);

CREATE TABLE supplier(
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL
);

CREATE TABLE medicine(
    medicine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    CHECK (unit_price > 0),
    CHECK (stock >= 0)
);

-- Junction table
CREATE TABLE suppliermedicine(
    supplier_id BIGINT NOT NULL,
    medicine_id BIGINT NOT NULL,
    supply_price DECIMAL(10, 2) NOT NULL CHECK (supply_price > 0),
    PRIMARY KEY(supplier_id, medicine_id),
    FOREIGN KEY(supplier_id) REFERENCES supplier(supplier_id) ON DELETE RESTRICT,
    FOREIGN KEY(medicine_id) REFERENCES medicine(medicine_id) ON DELETE RESTRICT
);

-- Dependent tables
CREATE TABLE "order"(
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    order_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    FOREIGN KEY(client_id) REFERENCES client(client_id) ON DELETE RESTRICT,
    CHECK (total_price >= 0)
);

CREATE TABLE orderitem(
    orderitem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    medicine_id BIGINT NOT NULL,
    quantity INT NOT NULL CHECK(quantity > 0),
    unit_price DECIMAL(10, 2) NOT NULL CHECK(unit_price > 0),
    FOREIGN KEY(order_id) REFERENCES "order"(order_id) ON DELETE CASCADE,
    FOREIGN KEY(medicine_id) REFERENCES medicine(medicine_id) ON DELETE RESTRICT
);