DROP TABLE IF EXISTS orderitem CASCADE;
DROP TABLE IF EXISTS suppliermedicine CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS medicine CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS client CASCADE;

-- Independent tables
CREATE TABLE client(
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL
);

CREATE TABLE supplier(
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL
);

CREATE TABLE medicine(
    medicine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    CHECK (unit_price > 0),
    CHECK (stock >= 0)
);

-- Junction table
CREATE TABLE suppliermedicine(
    supplier_id BIGINT NOT NULL,
    medicine_id BIGINT NOT NULL,
    supply_price DECIMAL(10, 2) NOT NULL CHECK (supply_price > 0),
    PRIMARY KEY(supplier_id, medicine_id),
    FOREIGN KEY(supplier_id) REFERENCES supplier(supplier_id) ON DELETE RESTRICT,
    FOREIGN KEY(medicine_id) REFERENCES medicine(medicine_id) ON DELETE RESTRICT
);

-- Dependent tables
CREATE TABLE "order"(
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    order_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    FOREIGN KEY(client_id) REFERENCES client(client_id) ON DELETE RESTRICT,
    CHECK (total_price >= 0)
);

CREATE TABLE orderitem(
    orderitem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    medicine_id BIGINT NOT NULL,
    quantity INT NOT NULL CHECK(quantity > 0),
    unit_price DECIMAL(10, 2) NOT NULL CHECK(unit_price > 0),
    FOREIGN KEY(order_id) REFERENCES "order"(order_id) ON DELETE CASCADE,
    FOREIGN KEY(medicine_id) REFERENCES medicine(medicine_id) ON DELETE RESTRICT
);

CREATE VIEW detailed_order_summary AS
SELECT
    o.order_id,
    o.order_date,
    c.first_name AS client_first_name,
    c.last_name AS client_last_name,
    o.total_price,
    SUM(oi.quantity) AS total_items_count
FROM "order" o
JOIN client c ON o.client_id = c.client_id
JOIN orderitem oi ON o.order_id = oi.order_id
GROUP BY o.order_id, c.client_id
ORDER BY o.order_date DESC;

CREATE VIEW medicine_min_supply_price AS
SELECT
    m.medicine_id,
    m.name AS medicine_name,
    m.unit_price AS current_selling_price,
    MIN(sm.supply_price) AS min_supply_price
FROM medicine m
JOIN suppliermedicine sm ON m.medicine_id = sm.medicine_id
GROUP BY m.medicine_id, m.name, m.unit_price
HAVING COUNT(sm.supplier_id) > 0;

-- Sukuria materializuotą vaizdą su duomenimis įvedimo metu
CREATE MATERIALIZED VIEW mv_supplier_stock_summary AS
SELECT
    s.name AS supplier_name,
    s.country,
    COUNT(sm.medicine_id) AS distinct_medicines_supplied,
    SUM(sm.supply_price * m.stock) AS total_potential_inventory_value
FROM supplier s
JOIN suppliermedicine sm ON s.supplier_id = sm.supplier_id
JOIN medicine m ON sm.medicine_id = m.medicine_id
GROUP BY s.supplier_id, s.name, s.country;

-- Non-unique index: Improves customer search by date
CREATE INDEX idx_order_date ON "order"(order_date);

-- Unique index: Ensures that there are no two suppliers with the same name
CREATE UNIQUE INDEX uix_supplier_name ON supplier(name);

-- Faster access to order items by medicine
CREATE INDEX idx_orderitem_medicine_id ON orderitem(medicine_id);
